config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects
  resources :contributions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'check_response', to: 'contributions#check_response'
  get 'users/show', to: 'users#show', as: 'my_dashboard'
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

    <ul class="navbar-nav ml-auto">
      <li class="nav-item mr-3" style="padding-top: 6px;">
          <%= link_to 'Home', '/',  class:"nav-link" %>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item mr-3" style="padding-top: 6px;">
      <%= link_to 'My dashboard', my_dashboard_path, class:"nav-link" %> 
      </li>
      <li class="nav-item mr-3" style="padding-top: 6px;">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %> 
      </li> 
      <% else %>
      <li class="nav-item mr-3" style="padding-top: 6px;">
      <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %> 
      </li>
      <li class="nav-item mr-3" style="padding-top: 6px;">
      <%= link_to "Sign in", new_user_session_path, class:"nav-link" %> 
      </li>
      <% end %>
    </ul>
  </div>
</nav>