config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects
  resources :contributions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'check_response', to: 'contributions#check_response'
  get 'users/show', to: 'users#show', as: 'my_dashboard'
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id                :bigint(8)        not null, primary key
#  name              :string
#  short_description :text
#  long_description  :text
#  goal              :float
#  image_data        :text
#  category_id       :bigint(8)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  aasm_state        :string
#

class Project < ApplicationRecord
  include AASM
  include ImageUploader::Attachment.new(:image)

  belongs_to :category
  has_many :contributions, dependent: :destroy
  has_many :counterparts, dependent: :destroy
  has_many :users, through: :contributions

  validates :name, presence: true, uniqueness: true, case_sensitive: false, format: { with: /\A[\x20-\x7E]+\z/, message: "Only alpha-numeric characters" }, length: { in: 3..30 }
  validates :goal, presence: true, numericality: { greater_than: 0 }
  validates :short_description, length: { in: 10..200 }, allow_blank: true
  validates :long_description, length: { in: 100..600 }, allow_blank: true

  aasm do
    state :draft, initial: true
    state :upcoming
    state :ongoing
    state :success
    state :failure

    event :start_upcoming do
      transitions from: :draft, to: :upcoming, guard: :can_upcome?
    end

    event :start_ongoing do
      transitions from: :upcoming, to: :ongoing, guard: :can_ongo?
    end

    event :succeed do
      transitions from: :ongoing, to: :success, guard: :completed?
    end

    event :fail do
      transitions from: :ongoing, to: :failure, guard: -> { !completed? }
    end
  end

  scope :pre_ongoing, -> { draft.or(upcoming) }

  def collect
    [sum = contributions.sum(:value), (sum / goal * 100).round(2)]
  end

  def rank
    contributions.collect(&:value).sort!.values_at(0, -1)
  end

  def can_upcome?
    name.present? && short_description.present? && long_description.present? && ( !image.nil? && image.size == 2)
  end

  def can_ongo?
    category_id.present? && (counterparts.size > 1)
  end

  def completed?
    return false unless collect[0] >= goal

    true
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/index.html.erb
<div class="row">
  <% @projects.each do |project| %>
    <div class="col-md-3 col-sm-12">
	  <div class="square-card">
	    <div class="card-header">
		  <div class="card-header_overlay">
			<span class="pill"><%= project.collect[1]%>%</span>
            <%= image_tag project.image_url(:thumb) %>
		  </div>
		</div>
	    <div class="card-title">
		  <h4><%= project.aasm_state %></h4>			
		</div>
		<div class="cta">
          <%= link_to "#{project.name}", project_path(project) %>
		</div>
	      </a>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="container" id="product-section">
  <div class="row">
    <div class="col-md-6">
      <div class="gallery">
        <div id='carousel-custom' class='carousel slide'>
          <div class='carousel-outer'>
            <div class='carousel-inner '>
              <div class='item active'>
              <%=  image_tag @project.image_url(:landscape)%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <h1 class="main-title"><%= @project.name %></h1>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <p class="description"><%= @project.long_description %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 bottom-rule">
          <h2 class="product-price">Completion: <%= @project.collect[1] %>%</h2>
        </div>
      </div>
      <div class="row'">
        <div class="col-md-12">
        <%= form_for Contribution.new, url: contributions_path, method: :post  do |f|%>
          <div class="row mb-3 mt-2">
            <div class="col-md-6">
              <div class="form-group">
              <%= f.collection_select :counterpart_id, @project.counterparts, :id, :name_with_price, class:"form-control select2"%>
              <%= f.hidden_field :project_id, value: @project.id%>
              </div>
            </div>
          </div>
          <div class="row add-to-cart">
            <div class="col-md-6">
            <% if user_signed_in? %>
              <%=f.submit 'Subscribe',class: "btn btn-outline-success btn-lg" %>
            <% end %>
            </div>
          </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>